### ISSUE TITLE
Fix for wrong pages totals when grid has filters

### ISSUE THREAD

**Issue by dfumagalli** [itstructure/laravel-grid-view#1]
There's an easily reproduced issue with the paginator page totals shown to the upper right of the grid.
If you filter the grid and the resulting rows are less than the default rows per page, then the total is wrong.

Example:
You have 32 rows split in 3 pages. The pages total correctly shows "Showing 1 to 10 of 32 entries".
Now you apply a filter that leaves out all rows but 3.

Expected: "Showing 1 to 3 of 3 entries".

Actually shown: "Showing 1 to 3 of 10 entries".

The fix is very simple:

In grid.blade.php, go to line #22 and replace the existing code with:

`'end' => '<b>' . min($paginator->perPage(), $paginator->total()) . '</b>',`

Now it'll show the expected value when filtered and not filtered alike.

**Comment by itstructure** [comment]
Fixed in a 1.0.12 release.
